name: frontend
description: A medical diagnosis chatbot application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Networking
  http: ^1.1.0
    # State management & storage
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  
  # UI/UX
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  flutter_animate: ^4.5.0
  
  # Text-to-speech capability
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
