follow_up_questions = {
    "flu": "Have you been feeling feverish, achy, or dealing with a dry cough lately?",
    "diabetes": "Have you noticed feeling unusually thirsty, needing to urinate more often, or feeling tired frequently?",
    "asthma": "Do you sometimes experience wheezing, shortness of breath, or tightness in your chest?",
    "pneumonia": "Are you dealing with a fever, cough, trouble breathing, or chest discomfort?",
    "bronchitis": "Have you had a persistent cough that brings up mucus?",
    "appendicitis": "Are you experiencing sharp abdominal pain, nausea, or a fever?",
    "tonsillitis": "Is your throat sore, making it hard to swallow, and do your tonsils feel swollen?",
    "anemia": "Do you often feel tired, dizzy, or short of breath?",
    "hepatitis": "Have you noticed yellowing of the skin or eyes, stomach pain, nausea, or dark-colored urine?",
    "meningitis": "Are you dealing with a high fever, stiff neck, intense headache, or sensitivity to light?",
    "tuberculosis": "Have you had a cough that won’t go away, unexpected weight loss, or night sweats?",
    "sinusitis": "Are you feeling pressure or pain in your face, struggling with nasal congestion, or getting headaches?",
    "psoriasis": "Have you noticed red, scaly patches on your skin that itch or burn?",
    "ulcerative colitis": "Are you experiencing frequent diarrhea, abdominal pain, or any rectal bleeding?",
    "crohn's disease": "Do you deal with chronic diarrhea, abdominal pain, or unexpected weight loss?",
    "hiv/aids": "Have you been feeling feverish, having night sweats, losing weight, or feeling unusually tired?",
    "epilepsy": "Have you experienced seizures, confusion, or unusual muscle twitching?",
    "stroke": "Have you felt sudden numbness, weakness, or difficulty speaking?",
    "heart attack": "Have you had chest discomfort, trouble breathing, or nausea?",
    "multiple sclerosis": "Are you struggling with muscle weakness, vision issues, or balance problems?",
    "parkinson's disease": "Have you noticed tremors, slower movements, or stiffness in your muscles?",
    "alzheimer's disease": "Have you been experiencing memory issues, confusion, or difficulty thinking clearly?",
    "osteoarthritis": "Are you dealing with joint pain, stiffness, or reduced movement?",
    "rheumatoid arthritis": "Do you often have painful, swollen joints, especially in the mornings?",
    "lupus": "Have you been feeling fatigued, dealing with joint pain, skin rashes, or a recurring fever?",
    "celiac disease": "Do you experience bloating, diarrhea, or feel like you're not absorbing nutrients well?",
    "gout": "Have you noticed sudden joint pain, swelling, or redness, especially in your big toe?",
    "hemorrhoids": "Are you experiencing rectal discomfort, itching, or swelling?",
    "urinary tract infection": "Do you feel a frequent urge to urinate, experience burning, or have pelvic discomfort?",
    "gallstones": "Are you feeling pain in your abdomen, experiencing nausea, or feeling bloated after eating?",
    "pancreatitis": "Have you had severe stomach pain, nausea, or vomiting?",
    "gerd": "Do you often feel heartburn, have acid reflux, or struggle with swallowing?",
    "otitis media": "Have you been experiencing ear pain, fever, or trouble hearing?",
    "conjunctivitis": "Are your eyes feeling red, itchy, watery, or producing discharge?",
    "glaucoma": "Have you noticed any gradual vision loss, eye discomfort, or seeing halos around lights?",
    "cataracts": "Are you struggling with blurry vision, faded colors, or double vision?",
    "hyperthyroidism": "Have you experienced unexplained weight loss, a rapid heartbeat, or feeling overly sensitive to heat?",
    "hypothyroidism": "Do you often feel tired, gain weight easily, or feel cold even when it’s warm?",
    "scabies": "Have you been dealing with an itchy rash that’s worse at night?",
    "ringworm": "Have you noticed a circular, red, scaly rash that’s clear in the middle?",
    "measles": "Are you experiencing a fever, cough, red eyes, or a skin rash?",
    "mumps": "Do you have swollen cheeks or jaw, fever, headaches, or muscle aches?"
}

detailed_follow_up = {
    "balance problems": [
        ("multiple sclerosis", "Have you experienced muscle weakness or any vision issues?"),
        ("parkinson's disease", "Have you noticed tremors or that your movements feel slower than usual?")
    ]
}
