"""
Translation module for multilingual support in the medical diagnosis app.
Supports English ("en") and Romanian ("ro").
"""
import logging

# --- Translation Dictionaries ---

# Format: "english_term_lowercase": "romanian_translation"
# Includes common symptoms, illnesses, and other relevant terms.
# Generated by combining the original list and the CSV data, then normalizing.
MEDICAL_TERMS_EN_RO = {
    # Symptoms
    "abdominal cramps": "crampe abdominale", # Merged from stomach cramps
    "abdominal pain": "durere abdominala",
    "aching body": "corp dureros",
    "acid reflux": "reflux acid",
    "acid regurgitation": "regurgitare acida",
    "acne": "acnee",
    "anxiety": "anxietate", # Added
    "asymmetry": "asimetrie",
    "back pain": "durere de spate",
    "balance issues": "probleme de echilibru",
    "blackheads": "puncte negre",
    "bleeding": "sangerare", # Added
    "bleeding gums": "gingii sangerande",
    "blisters": "basici", # Merged from painful blisters
    "bloating": "balonare",
    "blood in urine": "sange in urina",
    "blurred vision": "vedere incetosata",
    "boils": "furunculi", # From CSV
    "breathing": "respiratie", # Added
    "bruising": "vanatai", # From fracture/hemophilia
    "bulging lump": "umflatura proeminenta",
    "bullseye rash": "eruptie in forma de tinta",
    "burning": "senzatie de arsura", # From psoriasis
    "burning sensation": "senzatie de arsura",
    "burrow-like tracks": "urme ca niste tuneluri",
    "cataracts": "cataracta", # Illness as symptom? OK.
    "changing mole": "alunica care se schimba",
    "chest discomfort": "disconfort toracic",
    "chest pain": "durere in piept",
    "chest tightness": "constrictie toracica",
    "chills": "frisoane",
    "chronic diarrhea": "diaree cronica",
    "circular rash": "eruptie circulara",
    "cloudy urine": "urina tulbure",
    "cold intolerance": "intoleranta la frig",
    "cold sores": "herpes labial", # Illness as symptom? OK.
    "confusion": "confuzie",
    "congestion": "congestie", # Added from Flu description
    "conjunctivitis": "conjunctivita", # Illness as symptom? OK.
    "constipation": "constipatie",
    "cough": "tuse",
    "coughing": "tuse", # From Hantavirus/Asthma desc
    "cracked skin": "piele crapata",
    "dark urine": "urina inchisa la culoare",
    "deformity": "deformare",
    "dehydration": "deshidratare",
    "depressive episodes": "episoade depresive",
    "diarrhea": "diaree",
    "difficulty breathing": "dificultate in respiratie",
    "difficulty speaking": "dificultate in vorbire",
    "difficulty swallowing": "dificultate la inghitire",
    "discomfort": "disconfort",
    "dizziness": "ameteala",
    "double vision": "vedere dubla",
    "drooling": "salivare excesiva",
    "drooping mouth": "gura cazuta",
    "dry cough": "tuse seaca",
    "dry skin": "piele uscata",
    "ear pain": "durere de ureche",
    "easy bruising": "vanataie usoara",
    "exhaustion": "epuizare", # From Flu/Whooping Cough desc
    "excessive salivation": "salivare excesiva",
    "excessive thirst": "sete excesiva", # from Diabetes
    "eye discharge": "secretii oculare",
    "eye pain": "durere oculara",
    "facial pain": "durere faciala",
    "facial paralysis": "paralizie faciala",
    "faded colors": "culori estompate",
    "fatigue": "oboseala",
    "fever": "febra",
    "flare-ups": "episoade de agravare",
    "fluid drainage": "scurgeri de lichid", # From Otitis Media
    "food poisoning": "intoxicatie alimentara", # Illness as symptom? OK.
    "foul odor": "miros neplacut",
    "fracture": "fractura", # Illness as symptom? OK.
    "frequent infections": "infectii frecvente", # From Leukemia
    "frequent urination": "urinare frecventa",
    "gas": "gaze",
    "gradual vision loss": "pierderea treptata a vederii",
    "hallucinations": "halucinatii",
    "halos around lights": "halouri in jurul luminilor",
    "headache": "durere de cap",
    "headaches": "dureri de cap", # Plural from Hypertension
    "hearing": "auz", # Added
    "hearing difficulty": "dificultate de auz",
    "heart attack": "infarct miocardic", # Illness as symptom? OK.
    "heartburn": "arsuri la stomac",
    "heat intolerance": "intoleranta la caldura",
    "heavy menstrual bleeding": "sangerare menstruala abundenta",
    "high blood pressure": "tensiune arteriala ridicata",
    "high body temperature": "temperatura corporala ridicata",
    "high fever": "febra ridicata", # From Dengue/Pneumonia/etc.
    "high temperature": "temperatura ridicata", # From Flu description
    "hunger": "foame", # From Hypoglycemia
    "immune system decline": "declinul sistemului imunitar",
    "impulsive behavior": "comportament impulsiv",
    "increased thirst": "sete crescuta",
    "indigestion": "indigestie",
    "infertility": "infertilitate",
    "inflammation": "inflamatie",
    "intense itching": "mancarime intensa",
    "irregular bleeding": "sangerare neregulata",
    "irregular borders": "margini neregulate",
    "itching": "mancarime",
    "itchy": "mancarime", # Adjective form
    "itchy eyes": "ochi care mananca",
    "itchy rash": "eruptie cu mancarime",
    "jaundice": "icter", # Illness as symptom? OK.
    "joint pain": "durere articulara",
    "kidney problems": "probleme renale",
    "kidney stones": "pietre la rinichi", # Illness as symptom? OK.
    "lack of sweating": "lipsa transpiratiei",
    "loss of balance": "pierderea echilibrului",
    "loss of consciousness": "pierderea constientei",
    "loss of interest": "pierderea interesului",
    "loss of taste": "pierderea gustului",
    "low blood pressure": "tensiune arteriala scazuta",
    "lump": "nodul",
    "lung infections": "infectii pulmonare",
    "manic episodes": "episoade maniacale",
    "memory issues": "probleme de memorie",
    "memory loss": "pierderea memoriei",
    "mood swings": "schimbari de dispozitie",
    "morning stiffness": "rigiditate matinala",
    "mouth": "gura", # Added
    "mucus production": "productie de mucus",
    "multiple colors": "culori multiple",
    "muscle ache": "durere musculara",
    "muscle aches": "dureri musculare", # Plural from Mumps
    "muscle cramps": "crampe musculare",
    "muscle stiffness": "rigiditate musculara",
    "muscle twitching": "spasme musculare",
    "muscle weakness": "slabiciune musculara",
    "nasal congestion": "congestie nazala",
    "nausea": "greata",
    "neck": "gat", # Added
    "new mole": "alunica noua",
    "night sweats": "transpiratii nocturne",
    "nosebleeds": "sangerari nazale",
    "numbness": "amorteala",
    "nutrient deficiencies": "deficiente nutritionale",
    "often asymptomatic": "adesea asimptomatic", # Description, not symptom
    "oily skin": "piele grasa",
    "pain": "durere",
    "painful": "dureros", # Adjective
    "painful blisters": "basici dureroase",
    "painful periods": "menstruatie dureroasa",
    "pale skin": "piele palida",
    "pale stools": "scaune palide",
    "paralysis": "paralizie",
    "pelvic pain": "durere pelvina",
    "persistent cough": "tuse persistenta",
    "persistent sadness": "tristete persistenta",
    "pimples": "cosuri",
    "poor growth": "crestere deficitara",
    "prolonged bleeding": "sangerare prelungita",
    "pus": "puroi", # Added from 'filled with pus'
    "rapid heartbeat": "batai rapide ale inimii", # Also 'fast heartbeat'
    "rapid swelling": "umflare rapida",
    "rash": "eruptie cutanata", # Merged from spotty rash etc.
    "rectal bleeding": "sangerare rectala",
    "red eyes": "ochi rosii",
    "red scaly patches": "pete rosii scuamoase",
    "redness": "roseata",
    "reduced mobility": "mobilitate redusa",
    "respiratory symptoms": "simptome respiratorii", # Added from Flu description
    "rose-colored rash": "eruptie de culoare trandafirie",
    "runny nose": "nas care curge",
    "scaly rash": "eruptie scuamoasa",
    "seizures": "convulsii",
    "sensitivity to light": "sensibilitate la lumina",
    "sensitivity to sound": "sensibilitate la sunet",
    "severe abdominal pain": "durere abdominala severa",
    "severe cough": "tuse severa", # Added from Whooping Cough
    "severe coughing fits": "accese severe de tuse",
    "severe fatigue": "oboseala severa", # Added from Flu description
    "severe headache": "durere de cap severa",
    "severe muscle pain": "durere musculara severa",
    "severe pain": "durere severa",
    "severe sore throat": "durere in gat severa",
    "shingles": "herpes zoster", # Illness as symptom? OK.
    "shortness of breath": "respiratie dificila", # Merged with difficulty breathing
    "side pain": "durere laterala",
    "skin darkening": "intunecarea pielii",
    "skin discoloration": "decolorarea pielii",
    "skin rash": "eruptie cutanata", # Same as rash
    "sleep disturbances": "tulburari de somn",
    "slow heart rate": "ritm cardiac lent",
    "slow movements": "miscari lente",
    "sore throat": "durere in gat",
    "spotty rash": "eruptie cu pete",
    "stiff neck": "gat rigid",
    "stiffness": "rigiditate",
    "stomach cramps": "crampe stomacale",
    "stroke": "accident vascular cerebral", # Illness as symptom? OK.
    "sudden diarrhea": "diaree brusca",
    "sudden high temperature": "temperatura ridicata brusca",
    "sudden numbness": "amorteala brusca",
    "sweating": "transpiratie",
    "swelling": "umflatura",
    "swelling in legs": "umflarea picioarelor",
    "swollen": "umflat", # Adjective
    "swollen gums": "gingii umflate",
    "swollen salivary glands": "glande salivare umflate",
    "swollen tonsils": "amigdale umflate",
    "thick mucus": "mucus gros",
    "throat": "gat", # Added
    "tingling": "furnicaturi", # Merged from tingling sensation
    "tingling sensation": "senzatie de furnicaturi",
    "tiredness": "oboseala", # Added from Flu description
    "tissue death": "moartea tesuturilor",
    "tremors": "tremuraturi",
    "unexplained weight loss": "pierdere in greutate inexplicabila", # From Leukemia
    "unintended weight loss": "scadere in greutate neintentionata", # From Diabetes
    "unusual discharge": "secretii neobisnuite",
    "vision": "vedere", # Added
    "vision loss": "pierderea vederii",
    "vision problems": "probleme de vedere",
    "vomiting": "varsaturi", # Merged from nausea, vomiting
    "warmth": "caldura",
    "watery diarrhea": "diaree apoasa",
    "watery eyes": "ochi lacrimosi",
    "weakness": "slabiciune",
    "weight loss": "pierdere in greutate",
    "wheezing": "respiratie suieratoare",
    "whiteheads": "puncte albe",
    "whooping sound": "sunet de tuse convulsiva",
    "widespread pain": "durere generalizata",
    "yellowing of eyes": "ingalbenirea ochilor",
    "yellowing of skin": "ingalbenirea pielii",

    # Illnesses
    "acid reflux": "reflux acid", # Also a symptom
    "acne": "acnee", # Also a symptom
    "addisons disease": "boala addison",
    "alzheimers disease": "boala alzheimer",
    "anemia": "anemie",
    "aneurysm": "anevrism",
    "angina": "angina pectorala", # Added specific translation
    "appendicitis": "apendicita",
    "asthma": "astm",
    "bell's palsy": "paralizie bell",
    "bipolar disorder": "tulburare bipolara",
    "boils": "furunculi", # Also a symptom
    "brain tumor": "tumoare cerebrala",
    "bronchitis": "bronsita",
    "cancer": "cancer", # General term added
    "cataracts": "cataracta", # Also a symptom
    "celiac disease": "boala celiaca",
    "cervical cancer": "cancer de col uterin",
    "chickenpox": "varicela",
    "cholera": "holera",
    "chronic fatigue syndrome": "sindromul oboselii cronice", # Added
    "cluster headache": "cefalee cluster", # Added
    "cold sores": "herpes labial", # Also a symptom
    "common cold": "raceala comuna", # Specified 'comuna'
    "conjunctivitis": "conjunctivita", # Also a symptom
    "covid-19": "covid-19",
    "crohns disease": "boala crohn",
    "cystic fibrosis": "fibroza chistica",
    "dengue fever": "febra dengue",
    "depression": "depresie",
    "diabetes": "diabet",
    "eczema": "eczema",
    "endometriosis": "endometrioza",
    "epiglottitis": "epiglotita",
    "epilepsy": "epilepsie",
    "fibromyalgia": "fibromialgie",
    "flu": "gripa",
    "food poisoning": "intoxicatie alimentara", # Also a symptom
    "fracture": "fractura", # Also a symptom
    "gallstones": "calculi biliari", # More specific than 'pietre la fiere'
    "gangrene": "gangrena",
    "gastroenteritis": "gastroenterita",
    "gerd": "boala de reflux gastroesofagian", # GERD acronym is less common in RO
    "giardiasis": "giardiaza",
    "glaucoma": "glaucom",
    "gout": "guta",
    "guillain-barré syndrome": "sindrom guillain-barré",
    "hantavirus": "hantavirus",
    "heart attack": "infarct miocardic", # More specific
    "heart disease": "boala de inima",
    "heart failure": "insuficienta cardiaca", # Added
    "heat stroke": "insolatie",
    "hemophilia": "hemofilie",
    "hemorrhoids": "hemoroizi",
    "hepatitis": "hepatita",
    "hernia": "hernie",
    "hiv/aids": "hiv/sida",
    "hypercalcemia": "hipercalcemie",
    "hypertension": "hipertensiune",
    "hyperthyroidism": "hipertiroidism",
    "hypoglycemia": "hipoglicemie",
    "hypothyroidism": "hipotiroidism",
    "ibs": "sindrom de intestin iritabil", # IBS acronym less common
    "inner ear problems": "probleme ale urechii interne", # Added
    "irritable bowel syndrome": "sindrom de intestin iritabil", # Full name
    "jaundice": "icter", # Also a symptom
    "kidney stones": "calculi renali", # More specific than 'pietre la rinichi'
    "leukemia": "leucemie",
    "liver cirrhosis": "ciroza hepatica",
    "low blood pressure": "hipotensiune", # Medical term
    "lupus": "lupus",
    "lyme disease": "boala lyme",
    "malaria": "malarie",
    "measles": "rujeola",
    "melanoma": "melanom",
    "meningitis": "meningita",
    "migraine": "migrena",
    "multiple sclerosis": "scleroza multipla",
    "mumps": "oreion",
    "necrotizing fasciitis": "fasceita necrozanta",
    "osteoarthritis": "osteoartrita",
    "otitis media": "otita medie",
    "pancreatitis": "pancreatita",
    "parkinsons disease": "boala parkinson",
    "pneumonia": "pneumonie",
    "psoriasis": "psoriazis",
    "pulmonary embolism": "embolie pulmonara", # Added
    "rabies": "rabie",
    "rheumatoid arthritis": "artrita reumatoida",
    "ringworm": "dermatofitoză", # Tinea
    "scabies": "scabie",
    "sepsis": "septicemie", # Sepsis also used
    "shingles": "herpes zoster", # Also a symptom
    "sinusitis": "sinuzita",
    "stroke": "accident vascular cerebral", # Also a symptom
    "tension headache": "cefalee de tensiune", # Added
    "tonsillitis": "amigdalita",
    "tuberculosis": "tuberculoza",
    "typhoid fever": "febra tifoida",
    "ulcer": "ulcer", # Added
    "ulcerative colitis": "colita ulcerativa",
    "urinary tract infection": "infectie urinara",
    "whooping cough": "tuse convulsiva"
}    # Create the reverse mapping for RO -> EN
MEDICAL_TERMS_RO_EN = {v: k for k, v in MEDICAL_TERMS_EN_RO.items()}

# Add specific Romanian terms that need direct mapping (including common variations)
MEDICAL_TERMS_RO_EN.update({
    "dureri de cap": "headache",      # Add direct mapping for "dureri de cap"
    "durere de cap": "headache",      # Already exists but making explicit
    "dureri cap": "headache",         # Common shorthand
    "durere cap": "headache"          # Common shorthand
})

# --- Diagnosis Message Templates ---
# Keys: language_code -> template_name -> message_template
DIAGNOSIS_TEMPLATES = {
    "en": {
        "prediction": "Predicted illness: {illness} (Confidence: {confidence:.1%})",
        "more_likely": "Based on your answer, the diagnosis of {illness} is more likely.",
        "less_likely": "Based on your answer, {illness} may be less likely, or other conditions could be considered. Please consult a doctor.",
        "consult": "Please consult with a healthcare professional for an accurate diagnosis and treatment plan.",
        # "emergency": "EMERGENCY: Your symptoms might indicate a serious condition. Please seek immediate medical attention.", # Example
    },
    "ro": {
        "prediction": "Boala prezisă: {illness} (Încredere: {confidence:.1%})",
        "more_likely": "Pe baza răspunsului dumneavoastră, diagnosticul de {illness} este mai probabil.",
        "less_likely": "Pe baza răspunsului dumneavoastră, {illness} ar putea fi mai puțin probabil sau ar putea fi luate în considerare alte afecțiuni. Vă rugăm să consultați un medic.",
        "consult": "Vă rugăm să consultați un cadru medical pentru un diagnostic precis și un plan de tratament.",
        # "emergency": "URGENȚĂ: Simptomele dumneavoastră ar putea indica o afecțiune gravă. Vă rugăm să solicitați asistență medicală imediată.", # Example
    }
}

# --- Helper Functions ---

def get_diagnosis_message(language, template_key, **kwargs):
    """
    Retrieves and formats a diagnosis message template for the specified language.

    Args:
        language (str): Language code ('en' or 'ro').
        template_key (str): The key of the message template (e.g., 'prediction').
        **kwargs: Placeholder values for the template (e.g., illness="Flu", confidence=0.85).

    Returns:
        str: The formatted message string, defaulting to English if the language or key is not found.
    """
    lang_code = language if language in DIAGNOSIS_TEMPLATES else "en"
    template = DIAGNOSIS_TEMPLATES.get(lang_code, DIAGNOSIS_TEMPLATES["en"]).get(template_key)

    if template:
        try:
            return template.format(**kwargs)
        except KeyError as e:
            logging.error(f"Missing placeholder {e} for template '{template_key}' in language '{lang_code}'")
            # Return a generic message or the template itself
            return "Information message regarding diagnosis." # Generic fallback
    else:
        logging.warning(f"Template key '{template_key}' not found for language '{lang_code}'. Defaulting.")
        # Try fetching the English version as a fallback
        template_en = DIAGNOSIS_TEMPLATES["en"].get(template_key)
        if template_en:
             try:
                 return template_en.format(**kwargs)
             except KeyError:
                  return "Information message regarding diagnosis." # Generic fallback
        else:
            logging.error(f"Template key '{template_key}' not found in English either.")
            return "Diagnosis information available." # Final fallback


def translate_medical_term(term, to_romanian=False):
    """
    Translates a single medical term between English and Romanian.
    Case-insensitive matching. Returns the original term if no translation found.

    Args:
        term (str): The medical term to translate.
        to_romanian (bool): If True, translate EN->RO. If False, translate RO->EN.

    Returns:
        str: The translated term or the original term if not found.
    """
    if not term or not isinstance(term, str):
        return term # Return empty or non-string input as is

    term_lower = term.lower()

    if to_romanian:
        return MEDICAL_TERMS_EN_RO.get(term_lower, term)
    else:
        # Simple RO->EN lookup first
        translation = MEDICAL_TERMS_RO_EN.get(term_lower)
        if translation:
             return translation

        # Fallback: check if the input term contains a known RO term
        # This is less precise but can help with variations
        for ro_term, en_term in MEDICAL_TERMS_RO_EN.items():
             if ro_term in term_lower:
                 logging.debug(f"Partial match RO->EN: '{term_lower}' contains '{ro_term}', translating as '{en_term}'")
                 return en_term # Return the first partial match found

        return term # Return original if no match

def translate_illness(illness_name, language):
    """
    Translates an illness name to the target language using the medical term dictionary.

    Args:
        illness_name (str): The name of the illness (assumed English).
        language (str): The target language code ('en' or 'ro').

    Returns:
        str: The translated illness name, or the original if translation fails or language is 'en'.
    """
    if language == "ro":
        return translate_medical_term(illness_name, to_romanian=True)
    else:
        return illness_name # Return original name for English or unsupported languages